---
inlets:
  1:
    name: camera
    type: local_camera_cv2
    hidden: False
    parameters:
      device_id: 0
  2:
    name: light_conditions
    type: static_variable
    hidden: False
    parameters:
      value: natural
    metadata:
      unit: none
      interpretation: no artificial light switched on
      description: light conditions during experiment
  3:
    name: flow_regime
    type: static_variable
    hidden: False
    parameters:
      value: 0
    metadata:
      unit: none
      interpretation: flooded
      description: flow regime in reactor
  4:
    name: stirrer_rotational_speed
    type: opcua_variable
    parameters:
      server: 'opc.tcp://10.6.51.40:4840'
      username: admin
      password: wago
      node_ns: 4
      node_id: '|var|WAGO 750-8212 PFC200 G2 2ETH RS.Application.Services.Service_Stir_1.SetpointRPM.VOut'
    metadata:
      unit: rpm
      description: Setpoint for stirrer rotational speed
  5:
    name: fill_level
    type: opcua_variable
    parameters:
      server: 'opc.tcp://10.6.51.40:4840'
      username: admin
      password: wago
      node_ns: 4
      node_id: '|var|WAGO 750-8212 PFC200 G2 2ETH RS.Application.Services.Service_Fill_water_1.ActualWeight.V'
    metadata:
      unit: kg
      description: Read value of fill level in reactor
  6:
    name: pressure
    type: opcua_variable
    parameters:
      server: 'opc.tcp://10.6.51.40:4840'
      username: admin
      password: wago
      node_ns: 4
      node_id: '|var|WAGO 750-8212 PFC200 G2 2ETH RS.Application.Services.Service_Pressurize_1.ActualControllerPressure.V'
    metadata:
      unit: bar
      description: Read value of pressure in reactor
  7:
    name: gas_flow_rate
    type: opcua_variable
    parameters:
      server: 'opc.tcp://10.6.51.130:4840'
      username: admin
      password: wago
      node_ns: 4
      node_id: '|var|WAGO 750-8212 PFC200 G2 2ETH RS.Application.Services.Service_Transfer_Media.Flow_Read.V'
    metadata:
      unit: nlpm
      description: Read value of volumentric flow rate of gas
  8:
    name: temperature
    type: static_variable
    parameters:
      value: 20
    metadata:
      unit: degC
      description: Setpoint for temperatur in reactor jacket




processors:
  0:
    name: image_input
    type: input
    input_inlets:
      - camera
      - stirrer_rotational_speed
  1:
    name: saver
    type: save_on_disk
    parameters:
      save_path: '../data'
shell:
  type: periodical_local
  parameters:
    time_interval: 1000